apiVersion: v1
kind: Pod
metadata:
  name: xc16-mplabx-sonar-fmpp-python
spec:
  containers:
    - name: xc16-mplabx-sonar-fmpp-python
      image:  artifacts.microchip.com:7999/microchip/citd/bundles/xc16-mplabx-sonar-fmpp-python-yarn-node:latest
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 500m
          memory: 1500Mi
        limits:
          cpu: 1
          memory: 2Gi
    - name: buildtools
      image: artifacts.microchip.com:7999/microchip/buildtools/doxygen:1.8.15-r0
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 500m
          memory: 750Mi
        limits:
          cpu: 1
          memory: 1Gi
